name: mldd
channels:
  - pytorch
  - tpeulen
  - pyg
  - mordred-descriptor
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - absl-py=0.10.0
  - aiohttp=3.6.3
  - appnope=0.1.0
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.2.0
  - backcall=0.2.0
  - biopython=1.78
  - blas=1.0
  - bleach=3.2.1
  - blinker=1.4
  - bokeh=2.2.3
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.10.14
  - cachetools=4.1.1
  - cairo=1.16.0
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=3.1.1
  - cycler=0.10.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.10
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glew=2.1.0
  - glib=2.68.3
  - glib-tools=2.68.3
  - glm=0.9.9.4
  - google-auth=1.22.1
  - google-auth-oauthlib=0.4.1
  - googledrivedownloader=0.4
  - grpcio=1.31.0
  - icu=68.1
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lcms2=2.11
  - libclang=11.1.0
  - libcxx=12.0.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libglib=2.68.3
  - libiconv=1.16
  - libllvm11=11.1.0
  - libpng=1.6.37
  - libpq=12.3
  - libprotobuf=3.13.0.1
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp-base=1.1.0
  - libxml2=2.9.12
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - markdown=3.3.2
  - markupsafe=1.1.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mordred=1.2.0
  - multidict=4.7.6
  - mysql-common=8.0.22
  - mysql-libs=8.0.22
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - networkx=2.5
  - ninja=1.10.1
  - notebook=6.1.4
  - nspr=4.30
  - nss=3.67
  - numpy=1.19.1
  - numpy-base=1.19.1
  - oauthlib=3.1.0
  - olefile=0.46
  - openbabel=3.1.1
  - openssl=1.1.1h
  - packaging=20.4
  - pandas=1.1.3
  - pandoc=2.11
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.0
  - pip=20.2.4
  - pixman=0.40.0
  - pmw=2.0.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - protobuf=3.13.0.1
  - ptyprocess=0.6.0
  - py3dmol=1.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycairo=1.19.1
  - pycparser=2.20
  - pyg=2.0.1
  - pygments=2.7.1
  - pyjwt=1.7.1
  - pymol-open-source=2.4.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-louvain=0.14
  - python_abi=3.8
  - pytorch=1.9.1
  - pytorch-cluster=1.5.9
  - pytorch-scatter=2.0.8
  - pytorch-sparse=0.6.12
  - pytorch-spline-conv=1.2.1
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qt=5.12.9
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - rdkit=2021.03.5
  - readline=8.0
  - reportlab=3.5.51
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - scikit-learn=0.23.2
  - scipy=1.5.0
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=50.3.0
  - six=1.15.0
  - smina=2020.12.10
  - sqlalchemy=1.3.19
  - sqlite=3.35.5
  - tensorboard=2.2.1
  - tensorboard-plugin-wit=1.6.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.50.2
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - yarl=1.6.2
  - zeromq=4.3.3
  - zipp=3.3.1
  - zlib=1.2.11
  - zstd=1.4.5
prefix: /Users/tomek/opt/miniconda3/envs/mldd
